### ISSUE TITLE
Problems when running the example

### ISSUE THREAD

**Issue by CFGrote** [vanossj/pyAtlasBoneSegmentation#2]
After a fresh install. I get the following traceback when loading the example dicom data:

Traceback (most recent call last):
  File "src/pyAtlasSegmentation.py", line 352, in automate
    self.scanData = UserDicom(ctFilepath, niFilepath, joint=self.glWidget.worldJoint, sigma=2, resampleFactor=3, isolevel=350.0)
  File "src/InputDataTypes.py", line 402, in __init__
    self.isosurfaceModel3 = Polygonise(self.ctVolume3, 350.0).isosurface(progressDialogCallback=pd.setValue, joint=self.isosurfaceJoint)
AttributeError: UserDicom instance has no attribute 'isosurfaceJoint'

**Comment by vanossj** [comment]
I am not surprised, this code is 7 years old. I'll take a look at it but I'm not optimistic.

**Comment by CFGrote** [comment]
thanks anyway! Your reply is already more than I was hoping for ;)

Regards, Carsten
